# Generated by Django 4.2.16 on 2026-07-17 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0012_add_pos_machine_and_eservice'),
        ('core', '0007_branch_allowed_radius_branch_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('total_worked_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='إجمالي ساعات العمل')),
                ('total_delay_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='إجمالي ساعات التأخير')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='إجمالي الساعات الإضافية')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المستحق الأساسي')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مكافأة الإضافي')),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي الخصومات')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب الصافي')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الصرف')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.employee', verbose_name='الموظف')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll', to='accounting.journalentry', verbose_name='قيد الاستحقاق')),
            ],
            options={
                'verbose_name': 'مسير راتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('delay_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ساعات التأخير')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='الساعات الإضافية')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور والانصراف',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
