# Generated by Django 4.2.16 on 2026-06-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الضريبة')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النسبة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='حساب الضريبة')),
            ],
            options={
                'verbose_name': 'ضريبة',
                'verbose_name_plural': 'الضرائب',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='طريقة الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='حساب الدفع')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
    ]
