# Generated by Django 4.2.16 on 2026-07-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_rate_percent_tax_rate_treasury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='حساب الخزينة'),
        ),
    ]
