# Generated by Django 4.2.16 on 2026-07-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_branch'),
        ('accounting', '0004_alter_treasury_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المحفظة')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='حساب الدليل')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'محفظة إلكترونية',
                'verbose_name_plural': 'المحافظ الإلكترونية',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب البنكي')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='حساب الدليل')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'حسابات البنوك',
            },
        ),
    ]
