# Generated by Django 4.2.16 on 2026-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_ewallet_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد أول المدة'),
        ),
        migrations.AddField(
            model_name='ewallet',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد أول المدة'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد أول المدة'),
        ),
    ]
