# Generated by Django 4.2.16 on 2026-07-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_bankaccount_opening_balance_ewallet_opening_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ewallet',
            name='branch',
        ),
    ]
