# Generated by Django 4.2.16 on 2026-07-09 21:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0007_remove_bankaccount_branch_remove_ewallet_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم المصروف')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاريخ المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ (قبل الضريبة)')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة القيمة المضافة (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الضريبة المضافة')),
                ('withholding_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم والإضافة (%)')),
                ('withholding_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الخصم والإضافة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي الصافي')),
                ('description', models.TextField(blank=True, verbose_name='البيان / ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_debited', to='accounting.account', verbose_name='حساب المصروف')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_doc', to='accounting.journalentry', verbose_name='قيد اليومية')),
                ('payment_account', models.ForeignKey(limit_choices_to={'account_type': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_credited', to='accounting.account', verbose_name='حساب الدفع (الخزينة/البنك)')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
