# Generated by Django 4.2.16 on 2026-07-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_remove_invoiceline_tax_remove_invoiceline_tax_amount'),
        ('accounting', '0009_alter_expense_amount_expenseitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
