# Generated by Django 4.2.16 on 2026-07-10 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_account'),
        ('accounting', '0010_delete_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('RECEIPT', 'سند قبض'), ('PAYMENT', 'سند صرف')], max_length=15, verbose_name='نوع السند')),
                ('voucher_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم السند')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('EWALLET', 'محفظة إلكترونية')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مُرحل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.account', verbose_name='الحساب المقابل')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount', verbose_name='الحساب البنكي')),
                ('ewallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.ewallet', verbose_name='المحفظة الإلكترونية')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='accounting.journalentry', verbose_name='قيد اليومية')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='partners.partner', verbose_name='الشريك (عميل/مورد)')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.treasury', verbose_name='الخزينة')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'السندات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
