# Generated by Django 4.2.16 on 2026-07-10 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting'),
        ('invoicing', '0007_possession_invoice_pos_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0011_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الماكينة')),
                ('machine_type', models.CharField(choices=[('FAWRY', 'فوري'), ('AMAN', 'أمان'), ('BANK_VISA', 'ماكينة فيزا بنك'), ('INSTAPAY', 'إنستاباي'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='نوع الماكينة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد أول المدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_machines', to='accounting.account', verbose_name='حساب الدليل')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_machines', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'ماكينة دفع إلكتروني',
                'verbose_name_plural': 'ماكينات الدفع الإلكتروني',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم العملية')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('transaction_type', models.CharField(choices=[('CASH_OUT', 'سحب كاش (عميل يسحب من محفظته)'), ('CASH_IN', 'إيداع / تحويل (عميل يحول رصيد)'), ('MERCHANT_RECHARGE', 'شحن الماكينة من مندوب')], max_length=20, verbose_name='نوع العملية')),
                ('source_type', models.CharField(choices=[('MACHINE', 'ماكينة دفع'), ('EWALLET', 'محفظة إلكترونية')], default='MACHINE', max_length=10, verbose_name='مصدر الحركة')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الأصلي')),
                ('commission_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='عمولة المحل (الربح)')),
                ('commission_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رسوم المندوب (المصروف)')),
                ('description', models.TextField(blank=True, verbose_name='البيان')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('ewallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eservice_transactions', to='accounting.ewallet', verbose_name='المحفظة الإلكترونية')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eservice_transaction', to='invoicing.invoice', verbose_name='فاتورة المبيعات')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eservice_transaction', to='accounting.journalentry', verbose_name='قيد اليومية')),
                ('pos_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.posmachine', verbose_name='الماكينة')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eservice_transactions', to='accounting.treasury', verbose_name='الخزينة / الدرج')),
            ],
            options={
                'verbose_name': 'حركة خدمات دفع',
                'verbose_name_plural': 'حركات خدمات الدفع',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
