# Generated by Django 4.2.16 on 2026-07-15 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_partner_national_id'),
        ('accounting', '0012_add_pos_machine_and_eservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعدة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المعدة')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجار اليومي')),
                ('status', models.CharField(choices=[('AVAILABLE', 'متاحة'), ('RENTED', 'مؤجرة'), ('MAINTENANCE', 'في الصيانة')], default='AVAILABLE', max_length=20, verbose_name='حالة المعدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ بداية الإيجار')),
                ('days_rented', models.PositiveIntegerField(default=1, verbose_name='عدد أيام الإيجار')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة المتوقع')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر اليوم (وقت الإيجار)')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='إجمالي المبلغ')),
                ('payment_method', models.CharField(choices=[('CASH', 'كاش'), ('CREDIT', 'آجل')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط (مؤجرة)'), ('RETURNED', 'تم الإرجاع')], default='ACTIVE', max_length=20, verbose_name='حالة العقد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accrual_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_accrual', to='accounting.journalentry', verbose_name='قيد الاستحقاق')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('customer', models.ForeignKey(limit_choices_to={'partner_type__in': ['CUSTOMER', 'BOTH']}, on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='partners.partner', verbose_name='العميل')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.equipment', verbose_name='المعدة')),
                ('ewallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.ewallet', verbose_name='المحفظة (للكاش)')),
                ('payment_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_payment', to='accounting.journalentry', verbose_name='قيد السداد')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.treasury', verbose_name='الخزينة (للكاش)')),
            ],
        ),
    ]
