# Generated by Django 4.2.16 on 2026-07-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_pos_machine_and_eservice'),
        ('rentals', '0002_rental_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='opening_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_opening', to='accounting.journalentry', verbose_name='قيد الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة المعدة (رصيد افتتاحي)'),
        ),
    ]
