# Generated by Django 4.2.16 on 2026-07-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0009_invoice_discount_percentage_invoiceline_tax_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='معرف العميل (Client ID)')),
                ('client_secret', models.CharField(max_length=255, verbose_name='كلمة السر (Client Secret)')),
                ('taxpayer_activity_code', models.CharField(default='4741', max_length=10, verbose_name='كود النشاط (Activity Code)')),
                ('is_production', models.BooleanField(default=False, verbose_name='العملية الفعلية (Production Mode)')),
                ('company_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل الضريبي (Issuer ID)')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة (Issuer Name)')),
            ],
            options={
                'verbose_name': 'إعدادات الفاتورة الإلكترونية',
                'verbose_name_plural': 'إعدادات الفاتورة الإلكترونية',
            },
        ),
        migrations.CreateModel(
            name='EInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('SIGNED', 'تم التوقيع'), ('SUBMITTED', 'تم الإرسال للضرائب'), ('VALID', 'مقبولة (Valid)'), ('INVALID', 'مرفوضة (Invalid)'), ('ERROR', 'خطأ في الإرسال')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID الفاتورة بالضرائب')),
                ('submission_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الإرسال (Submission ID)')),
                ('eta_response', models.JSONField(blank=True, null=True, verbose_name='رد مصلحة الضرائب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice_log', to='invoicing.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'سجل الفاتورة الإلكترونية',
                'verbose_name_plural': 'سجل الفواتير الإلكترونية',
            },
        ),
    ]
