# Generated by Django 4.2.16 on 2026-07-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoicelog',
            name='status',
            field=models.CharField(choices=[('WAITING_APPROVAL', 'في انتظار التأكيد'), ('PENDING', 'قيد الانتظار'), ('SIGNED', 'تم التوقيع'), ('SUBMITTED', 'تم الإرسال للضرائب'), ('VALID', 'مقبولة (Valid)'), ('INVALID', 'مرفوضة (Invalid)'), ('ERROR', 'خطأ في الإرسال')], default='WAITING_APPROVAL', max_length=20, verbose_name='الحالة'),
        ),
    ]
