# Generated by Django 4.2.16 on 2026-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0002_alter_einvoicelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoicelog',
            name='signed_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='ملف التوقيع (JSON)'),
        ),
    ]
