# Generated by Django 4.2.16 on 2026-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0003_einvoicelog_signed_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxintegrationsettings',
            name='enable_einvoicing',
            field=models.BooleanField(default=True, verbose_name='تفعيل المنظومة (إرسال الفواتير)'),
        ),
    ]
