# Generated by Django 4.2.16 on 2026-06-29 12:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='الاسم')),
                ('partner_type', models.CharField(choices=[('CUSTOMER', 'عميل'), ('SUPPLIER', 'مورد'), ('BOTH', 'عميل ومورد')], default='CUSTOMER', max_length=10, verbose_name='نوع الشريك')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='الموبايل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('credit_limit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='حد الائتمان')),
                ('payment_terms_days', models.IntegerField(default=30, verbose_name='مدة السداد (أيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payable_account', models.ForeignKey(blank=True, help_text='تُستخدم لتسجيل المشتريات الآجلة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_partners', to='accounting.account', verbose_name='حساب الذمم الدائنة')),
                ('receivable_account', models.ForeignKey(blank=True, help_text='تُستخدم لتسجيل المبيعات الآجلة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_partners', to='accounting.account', verbose_name='حساب الذمم المدينة')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('RECEIPT', 'تحصيل من عميل'), ('PAYMENT', 'دفع لمورد')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('method', models.CharField(choices=[('CASH', 'نقدي'), ('CARD', 'بطاقة'), ('BANK', 'تحويل بنكي')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.branch', verbose_name='الفرع')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.partner', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
