# Generated by Django 4.2.16 on 2026-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_rate_percent_tax_rate_treasury'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_partners', to='accounting.account', verbose_name='الحساب الموحد'),
        ),
    ]
