# Generated by Django 4.2.16 on 2026-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='subject_to_withholding_tax',
            field=models.BooleanField(default=False, verbose_name='يخضع لضريبة الخصم والإضافة'),
        ),
    ]
