# Generated by Django 4.2.16 on 2026-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_subject_to_withholding_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم القومي'),
        ),
    ]
