# Generated by Django 4.2.16 on 2026-07-16 11:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_partner_national_id'),
        ('core', '0006_alter_systemsetting_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_alter_product_product_type_serialitem'),
        ('accounting', '0012_add_pos_machine_and_eservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=200, verbose_name='موديل الجهاز')),
                ('device_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='السيريال/IMEI (اختياري)')),
                ('device_condition_on_receipt', models.TextField(blank=True, verbose_name='حالة الجهاز عند الاستلام')),
                ('issue_description', models.TextField(verbose_name='وصف العطل')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'جاري العمل'), ('WAITING_PARTS', 'في انتظار قطع الغيار'), ('DONE', 'جاهز للتسليم'), ('DELIVERED', 'تم التسليم')], default='PENDING', max_length=20, verbose_name='حالة التذكرة')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='التكلفة التقديرية')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المصنعية (أجر العمل)')),
                ('warranty_days', models.IntegerField(default=0, verbose_name='أيام الضمان بعد الصيانة')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت التسليم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='core.branch', verbose_name='الفرع')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tickets', to='partners.partner', verbose_name='العميل')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_tickets', to=settings.AUTH_USER_MODEL, verbose_name='سلّمه')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('parent_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tickets', to='maintenance.maintenanceticket', verbose_name='تذكرة الضمان الأصلية')),
                ('serial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='inventory.serialitem', verbose_name='جهاز من مخزوننا (اختياري)')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='الفني المختص')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_receipts', to='accounting.treasury', verbose_name='الخزينة (لتحصيل المبلغ)')),
            ],
            options={
                'verbose_name': 'تذكرة صيانة',
                'verbose_name_plural': 'تذاكر الصيانة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='الكمية')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع للعميل')),
                ('actual_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='التكلفة الفعلية (من المخزون)')),
                ('stock_deducted', models.BooleanField(default=False, verbose_name='تم خصم المخزون')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_parts', to='inventory.product', verbose_name='قطعة الغيار')),
                ('serial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_parts', to='inventory.serialitem', verbose_name='السيريال (للقطع المسروِلة)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.maintenanceticket', verbose_name='التذكرة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_parts', to='inventory.warehouse', verbose_name='مخزن السحب')),
            ],
            options={
                'verbose_name': 'قطعة غيار مستهلكة',
                'verbose_name_plural': 'قطع الغيار المستهلكة في الصيانة',
            },
        ),
    ]
