# Generated by Django 4.2.16 on 2026-07-16 11:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_pos_machine_and_eservice'),
        ('inventory', '0010_alter_product_product_type_serialitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_milestone', models.DecimalField(decimal_places=2, help_text='مثال: 1000 — أي عمولة لكل 1000 جنيه مبيعات في هذه الفئة', max_digits=12, verbose_name='شريحة المبيعات (ج.م)')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='مثال: 5 — أي 5 جنيه لكل 1000 جنيه مبيعات', max_digits=8, verbose_name='مبلغ العمولة لكل شريحة (ج.م)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule', to='inventory.category', verbose_name='الفئة الرئيسية')),
            ],
            options={
                'verbose_name': 'قاعدة عمولة',
                'verbose_name_plural': 'لائحة قواعد العمولات',
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('DAILY', 'يومي'), ('MONTHLY', 'شهري'), ('YEARLY', 'سنوي')], max_length=10, verbose_name='الفترة')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_sales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='إجمالي المبيعات')),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='العمولة المستحقة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الصرف')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='inventory.category', verbose_name='الفئة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='قيد صرف العمولة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to=settings.AUTH_USER_MODEL, verbose_name='الموظف / الكاشير')),
            ],
            options={
                'verbose_name': 'سجل عمولة',
                'verbose_name_plural': 'سجلات العمولات',
                'ordering': ['-period_start', 'user'],
                'unique_together': {('user', 'category', 'period', 'period_start')},
            },
        ),
    ]
