[Settings]
# رابط الاتصال بالنظام (حسب إذا كان العميل سحابي أو محلي)
 BASE_URL = http://127.0.0.1:8080
#BASE_URL = https://easymbstore.com

# مسار ملف الـ DLL الخاص بتوكن التوقيع الإلكتروني (مثل ePass2003)
DLL_PATH = C:\Windows\System32\eps2003csp11.dll
