# Generated by Django 4.2.16 on 2026-06-29 12:48

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, verbose_name='اسم السوبر ماركت')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم المالك')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='مدفوع حتى')),
                ('on_trial', models.BooleanField(default=True, verbose_name='على فترة تجريبية')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='خطة الاشتراك')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'نطاق',
                'verbose_name_plural': 'النطاقات',
            },
        ),
    ]
