# Generated by Django 4.2.16 on 2026-06-29 12:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_original', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='الكمية الأصلية')),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='الكمية المتبقية')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='تكلفة الوحدة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دفعة مخزون',
                'verbose_name_plural': 'دفعات المخزون',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='الاسم بالإنجليزية')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='باركود')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود المنتج')),
                ('unit', models.CharField(choices=[('KG', 'كيلو'), ('PIECE', 'قطعة'), ('LITER', 'لتر'), ('BOX', 'كرتونة'), ('DOZEN', 'دستة'), ('GRAM', 'جرام'), ('METER', 'متر'), ('PACK', 'عبوة')], default='PIECE', max_length=10, verbose_name='وحدة القياس')),
                ('sale_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='سعر البيع')),
                ('min_sale_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='أدنى سعر بيع')),
                ('last_purchase_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='آخر سعر شراء')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('14'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('min_stock_level', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='حد أدنى للمخزون')),
                ('max_stock_level', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='حد أقصى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='السماح بمخزون سالب')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المستودع')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المستودع')),
                ('is_cold_storage', models.BooleanField(default=False, verbose_name='تبريد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'وارد - شراء'), ('OUT', 'صادر - بيع'), ('TRANSFER_IN', 'تحويل وارد'), ('TRANSFER_OUT', 'تحويل صادر'), ('ADJUSTMENT_IN', 'تسوية زيادة'), ('ADJUSTMENT_OUT', 'تسوية نقص'), ('RETURN_IN', 'مرتجع وارد'), ('RETURN_OUT', 'مرتجع صادر')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة الوحدة')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorybatch', verbose_name='الدفعة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product', verbose_name='المنتج'),
        ),
    ]
