# Generated by Django 4.2.16 on 2026-06-29 14:59

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'تسوية مخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة الوحدة (تقديرية)')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment', verbose_name='التسوية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند تسوية',
                'verbose_name_plural': 'بنود التسوية',
            },
        ),
    ]
