# Generated by Django 4.2.16 on 2026-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment_stockadjustmentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='egs_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود EGS'),
        ),
        migrations.AddField(
            model_name='product',
            name='gs1_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود GS1'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الصنف الداخلي'),
        ),
        migrations.CreateModel(
            name='ProductUoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base', models.BooleanField(default=False, verbose_name='وحدة أساسية')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='معامل التحويل')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='باركود الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='inventory.product', verbose_name='المنتج')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة قياس المنتج',
                'verbose_name_plural': 'وحدات قياس المنتج',
            },
        ),
    ]
