# Generated by Django 4.2.16 on 2026-07-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_branch'),
        ('inventory', '0004_unitofmeasure_product_egs_code_product_gs1_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='سعر البيع بالفرع')),
                ('min_sale_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='أقل سعر بيع بالفرع')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
