# Generated by Django 4.2.16 on 2026-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('OUT', 'إعدام / تسوية نقص'), ('IN', 'تسوية بالزيادة'), ('OPENING', 'رصيد افتتاحي')], default='OUT', max_length=10, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='السبب / البيان'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'وارد - شراء'), ('OUT', 'صادر - بيع'), ('TRANSFER_IN', 'تحويل وارد'), ('TRANSFER_OUT', 'تحويل صادر'), ('ADJUSTMENT_IN', 'تسوية زيادة'), ('ADJUSTMENT_OUT', 'تسوية نقص'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('RETURN_IN', 'مرتجع وارد'), ('RETURN_OUT', 'مرتجع صادر')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
