# Generated by Django 4.2.16 on 2026-07-11 20:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockadjustment_adjustment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة ضريبة الخصم والإضافة %'),
        ),
    ]
