# Generated by Django 4.2.16 on 2026-07-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_withholding_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_open_price',
            field=models.BooleanField(default=False, verbose_name='سعر مفتوح في نقطة البيع'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PRODUCT', 'منتج مخزني'), ('SERVICE', 'خدمة / مصنعية')], default='PRODUCT', max_length=10, verbose_name='نوع المنتج'),
        ),
    ]
