# Generated by Django 4.2.16 on 2026-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_is_open_price_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة'),
        ),
    ]
