# Generated by Django 4.2.16 on 2026-07-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockmovement_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PRODUCT', 'منتج مخزني'), ('SERVICE', 'خدمة / مصنعية'), ('SERIALIZED', 'منتج برقم تسلسلي (موبايل/أجهزة)')], default='PRODUCT', max_length=15, verbose_name='نوع المنتج'),
        ),
        migrations.CreateModel(
            name='SerialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='رقم السيريال / IMEI')),
                ('condition', models.CharField(choices=[('NEW', 'جديد'), ('USED', 'مستعمل')], default='NEW', max_length=20, verbose_name='الحالة')),
                ('storage', models.CharField(blank=True, max_length=50, null=True, verbose_name='مساحة التخزين')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_sold', models.BooleanField(default=False, verbose_name='تم البيع؟')),
                ('actual_cost', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='التكلفة الفعلية لهذه القطعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory.product', verbose_name='المنتج (الموديل)')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_items', to='inventory.warehouse', verbose_name='المخزن الحالي')),
            ],
            options={
                'verbose_name': 'منتج بسيريال',
                'verbose_name_plural': 'المنتجات بالسيريال',
                'ordering': ['-created_at'],
            },
        ),
    ]
