# Generated by Django 4.2.16 on 2026-07-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_product_type_serialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_imei',
            field=models.BooleanField(default=False, verbose_name='له أرقام IMEI (موبايلات)'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_serial',
            field=models.BooleanField(default=False, verbose_name='له رقم تسلسلي (S/N)'),
        ),
        migrations.AddField(
            model_name='serialitem',
            name='imei_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI 1'),
        ),
        migrations.AddField(
            model_name='serialitem',
            name='imei_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI 2'),
        ),
        migrations.AlterField(
            model_name='serialitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم السيريال (S/N)'),
        ),
    ]
