# Generated by Django 4.2.16 on 2026-07-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_has_imei_product_has_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialitem',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='مرتجع للمورد'),
        ),
        migrations.AlterField(
            model_name='serialitem',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='تم بيعه'),
        ),
        migrations.AlterField(
            model_name='serialitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_items', to='inventory.warehouse', verbose_name='مستودع التخزين'),
        ),
    ]
