# Generated by Django 4.2.16 on 2026-07-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='السماح بالبيع بالسالب')),
                ('auto_print_receipt', models.BooleanField(default=True, verbose_name='الطباعة التلقائية للإيصال')),
                ('allow_pos_price_modification', models.BooleanField(default=False, verbose_name='تعديل الأسعار في نقطة البيع')),
                ('apply_vat_by_default', models.BooleanField(default=True, verbose_name='تطبيق الضريبة الافتراضي')),
                ('large_amount_requires_customer', models.DecimalField(decimal_places=2, default=0, help_text='0 تعني غير مفعل', max_digits=10, verbose_name='إلزام اختيار عميل للمبالغ الأكبر من')),
                ('enable_expiry_tracking', models.BooleanField(default=False, verbose_name='تتبع تاريخ الصلاحية')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='الحد الأدنى لتنبيهات المخزون')),
                ('auto_post_journals', models.BooleanField(default=True, verbose_name='الترحيل التلقائي للقيود')),
                ('store_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المتجر للإيصال')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=100, verbose_name='السجل التجاري')),
                ('receipt_footer', models.TextField(blank=True, verbose_name='رسالة أسفل الإيصال')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
