# Generated by Django 4.2.16 on 2026-07-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='pos_price_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='هامش التعديل المسموح للسعر (%)'),
        ),
    ]
