# Generated by Django 4.2.16 on 2026-07-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsetting_pos_price_margin_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'permissions': [('view_sales_reports', 'Can view sales reports'), ('view_purchases_reports', 'Can view purchases reports'), ('view_inventory_reports', 'Can view inventory reports'), ('view_accounting_reports', 'Can view accounting reports')], 'verbose_name': 'إعدادات النظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
    ]
