# Generated by Django 4.2.16 on 2026-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemsetting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allowed_radius',
            field=models.IntegerField(default=50, verbose_name='نطاق السماح (بالمتر)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='خط العرض (Latitude)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='خط الطول (Longitude)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب الأساسي (اختياري)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_working_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='ساعات العمل اليومية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='deduction_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قيمة الخصم للساعة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قيمة ساعة العمل العادية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قيمة الإضافي للساعة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ميعاد الانصراف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ميعاد الحضور'),
        ),
    ]
