# Generated by Django 4.2.16 on 2026-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('plan_type', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20, verbose_name='نوع الخطة')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('max_branches', models.IntegerField(default=1, verbose_name='أقصى عدد فروع')),
                ('max_users', models.IntegerField(default=5, verbose_name='أقصى عدد مستخدمين')),
                ('max_warehouses_per_branch', models.IntegerField(default=2, verbose_name='أقصى مستودعات لكل فرع')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='مميزات الخطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price'],
            },
        ),
    ]
