# Generated by Django 4.2.16 on 2026-06-29 12:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('accounting', '0001_initial'),
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_type', models.CharField(choices=[('SALE', 'فاتورة مبيعات'), ('PURCHASE', 'فاتورة مشتريات'), ('RETURN_SALE', 'مرتجع مبيعات'), ('RETURN_PURCHASE', 'مرتجع مشتريات')], max_length=20, verbose_name='نوع الفاتورة')),
                ('date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('payment_type', models.CharField(choices=[('CASH', 'نقدي'), ('CREDIT', 'آجل'), ('CARD', 'بطاقة')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّلة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=15, verbose_name='الحالة')),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='إجمالي قبل الضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة الخصم')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='ضريبة القيمة المضافة')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='الإجمالي النهائي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.branch', verbose_name='الفرع')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_invoices', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.partner', verbose_name='الشريك (عميل/مورد)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='سعر الوحدة')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة الخصم')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('14'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='الإجمالي (بعد خصم، قبل ضريبة)')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة الضريبة')),
                ('cogs_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة البضاعة المباعة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفاتورة',
            },
        ),
    ]
