# Generated by Django 4.2.16 on 2026-07-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_unitofmeasure_product_egs_code_product_gs1_code_and_more'),
        ('accounting', '0003_rename_rate_percent_tax_rate_treasury'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='eta_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='eta_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.tax'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productuom', verbose_name='وحدة القياس'),
        ),
    ]
