# Generated by Django 4.2.16 on 2026-07-09 06:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_remove_invoiceline_tax_rate_invoice_eta_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wht_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة الخصم والإضافة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wht_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة ضريبة الخصم والإضافة (%)'),
        ),
    ]
