# Generated by Django 4.2.16 on 2026-07-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_rate_percent_tax_rate_treasury'),
        ('invoicing', '0003_invoice_vat_percentage_invoice_wht_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='treasury',
            field=models.ForeignKey(blank=True, help_text='تستخدم فقط في الفواتير النقدية', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.treasury', verbose_name='الخزينة/البنك'),
        ),
    ]
