# Generated by Django 4.2.16 on 2026-07-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_ewallet_bankaccount'),
        ('invoicing', '0004_invoice_treasury'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ewallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.ewallet', verbose_name='المحفظة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'نقدي'), ('CREDIT', 'آجل'), ('CARD', 'بطاقة'), ('EWALLET', 'محفظة إلكترونية'), ('BANK_TRANSFER', 'تحويل بنكي')], default='CASH', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='treasury',
            field=models.ForeignKey(blank=True, help_text='تستخدم فقط في الفواتير النقدية', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.treasury', verbose_name='الخزينة'),
        ),
    ]
