# Generated by Django 4.2.16 on 2026-07-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoice_bank_account_invoice_ewallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='tax_amount',
        ),
    ]
