# Generated by Django 4.2.16 on 2026-07-10 14:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_systemsetting'),
        ('invoicing', '0006_remove_invoiceline_tax_remove_invoiceline_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='رصيد الافتتاح (العهدة)')),
                ('closing_balance_expected', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='الرصيد المتوقع')),
                ('closing_balance_actual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='الرصيد الفعلي')),
                ('difference', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='العجز / الزيادة')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='core.branch', verbose_name='الفرع')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='accounting.treasury', verbose_name='الخزينة/الدرج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
            ],
            options={
                'verbose_name': 'وردية نقاط البيع',
                'verbose_name_plural': 'ورديات نقاط البيع',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.possession', verbose_name='وردية نقطة البيع'),
        ),
    ]
