# Generated by Django 4.2.16 on 2026-07-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_pos_machine_and_eservice'),
        ('invoicing', '0007_possession_invoice_pos_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pos_machine',
            field=models.ForeignKey(blank=True, help_text='تستخدم فقط في فواتير الدفع بالبطاقة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.posmachine', verbose_name='ماكينة الدفع الإلكتروني'),
        ),
    ]
