# Generated by Django 4.2.16 on 2026-07-11 20:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_add_pos_machine_and_eservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الخصم الإجمالي (%)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='الإجمالي النهائي'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='wht_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة الخصم والإضافة'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='wht_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة ضريبة الخصم والإضافة %'),
        ),
    ]
