# Generated by Django 4.2.16 on 2026-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoice_discount_percentage_invoiceline_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='e_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة الإلكترونية'),
        ),
    ]
