# Generated by Django 4.2.16 on 2026-07-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_product_type_serialitem'),
        ('invoicing', '0010_invoice_e_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='serial_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.serialitem', verbose_name='السيريال (للمنتجات المسروِلة)'),
        ),
    ]
