# Generated by Django 4.2.16 on 2026-07-18 08:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_invoiceline_serial_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parent_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoices', to='invoicing.invoice', verbose_name='الفاتورة الأصلية (للمرتجعات)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='الكمية المرتجعة مسبقاً'),
        ),
    ]
